[package]
name = "day17-23"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
toodee = "0.5.0"
common = { path = "../../common" }